### ISSUE TITLE
SSR Example

### ISSUE THREAD

**Issue by popuguytheparrot** [nanostores/i18n#2]
It would be very nice to see an example for SSR with for example nextjs

**Comment by ai** [comment]
Does it helps? https://github.com/nanostores/i18n#server-side-rendering

**Comment by ai** [comment]
> in this example let locale, i18n will shared for all users on each request.

You need to use your framework’s APIs for this. You can avoid using a separated file for every store and initialize all stores together in some functions like `buildContext()`. Or you can export store builder from every file.

> So, in Next.js i need serialised data to gssp props

Sorry, I do not use Next.js to suggest exact solution.

If you need some specific API, ask for it.

**Comment by ai** [comment]
I am closing this issue. We have a similar “What is the best SSR integration” discussion in main Nano Stores repository.

But without an API suggestions from Next.js users I can’t help.
