### ISSUE TITLE
does nanostores/i18n process process lists in international way?

### ISSUE THREAD

**Issue by iambumblehead** [nanostores/i18n#20]
How should one generate list-using messages with nanostores/i18n? Is there another recommended way using nanostores/i18n?
```javascript
// input_missing_params -> "Validation failed, missing fields: {fields}"
getMessage( messages, 'en-US', 'input_missing_params', { fields: [ 'email', 'name' ].join( ', ' ) } )
```

Languages I'm working with aren't affected by different list formats like these: https://github.com/jamesplease/i18n-list-generator.js

**Comment by ai** [comment]
Browsers and Node.js have built-in API for that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat
