### ISSUE TITLE
Usage in sandboxes

### ISSUE THREAD

**Issue by dartess** [nanostores/i18n#28]
I tried to put a demo with a working example in `codesandbox` and `stackblitz`, and in both cases I got `Cannot use 'import.meta' outside a module`. is it possible to wrap this part in `try/catch`?

**Comment by ai** [comment]
Sure! Please send PR

**Comment by dartess** [comment]
It seems that this cannot be fixed from the library side. The error occurs at the parsing stage and also occurs with some other libraries.

I was able to run demo in stackblitz in ViteJS project running in WebContainers environment
