### ISSUE TITLE
Not able to change language

### ISSUE THREAD

**Issue by adamgajzlerowicz** [nanostores/i18n#37]
I am trying to change the language, but still the value of `baseTranslation` is used.
Am I dong something wrong? This is my implementation:

```
import { createI18n, localeFrom, browser } from '@nanostores/i18n'
import { persistentAtom } from '@nanostores/persistent'
import { fetchJson } from 'fetch-json'

export const setting = persistentAtom<string | undefined>('locale', undefined)

export const locale = localeFrom(
  setting,
  browser({
    available: ['en', 'pl'],
    fallback: 'en',
  }),
)

console.log(locale.get()) // logs en

export const i18n = createI18n(locale, {
  async get(code) {
    console.log('hello') // is never called
    if (code === 'pl') {
      return Promise.resolve({})
    }
    return fetchJson.get(`/translations/${code}.json`)
  },
})

export const navigation = i18n('navigation', {
  app: 'Aplikacja',
})

console.log(navigation.value?.app) // logs polish translation
```

Thank you!

**Comment by ai** [comment]
Try to replace last line to proper subscribe:

```js
navigation.subscribe(t => {
  console.log(t.app)
})
```

(All stores are lazy and without `subscribe` you are not calling store’s initializers)

**Comment by adamgajzlerowicz** [comment]
This also yields in a wrong language. 
Could you possibly take a look at this minimal reproducible example?

I am not sure what I am doing wrong. 
https://github.com/adamgajzlerowicz/astro-i18n

The way I set it up, is that on flag click, I go to api endpoint to change set the language in the cookie, and redirect back to root url.
Then I would like to be able to get that cookie back and render translated content based on that.

Appreciate your help!

**Comment by ai** [comment]
Got it!

The problem is that you are using `pl` as a base locale. In this case you need to set [`baseLocale`](https://github.com/nanostores/i18n/blob/main/create-i18n/index.d.ts#L84) option to `createI18n`.

By default, I18n is using `en` as base locale, and it thinks that `app: 'Aplikacja'` is English translations.

**Comment by adamgajzlerowicz** [comment]
Thank you for looking into this.
I added the [option](https://github.com/adamgajzlerowicz/astro-i18n/commit/bfb85050665e55940d5d7cd25cbcb3379de75b69) but the behaviour is still the same

**Comment by ai** [comment]
OK, I will look. But very likely that I will be able to do it only on weekend or later.

If you have time, it is better to debug the code (maybe we have a bug in `baseLocale` I didn’t test well on real project). The code inside is very simple.

**Comment by adamgajzlerowicz** [comment]
I will have a go too. At least now I know that general approach I am taking is not fundamentally wrong.
