### ISSUE TITLE
Fast Refresh warning

### ISSUE THREAD

**Issue by openscript** [nanostores/i18n#38]
I'm using version 0.12.2 and followed the README.

```tsx
import { Button, Container, Paper, PasswordInput, TextInput, Title } from "@quassel/ui";
import { createFileRoute } from "@tanstack/react-router";
import { i18n } from "../stores/i18n";
import { useStore } from "@nanostores/react";

export const messages = i18n("sessionRoute", {
  title: "Sign in",
  emailLabel: "Email",
  emailPlaceholder: "fraenzy.tobler@example.ch",
});

export const Route = createFileRoute("/session")({
  component: () => {
    const t = useStore(messages);
    return (
      <Container size={420} my={40}>
        <Title ta="center">{t.title}</Title>

        <Paper withBorder shadow="md" p={30} mt={30} radius="md">
          <TextInput label={t.emailLabel} placeholder={t.emailPlaceholder} required />
          <PasswordInput label="Password" placeholder="Your password" required mt="md" />
          <Button fullWidth mt="xl">
            Sign in
          </Button>
        </Paper>
      </Container>
    );
  },
});
```

When HMR is active I get the following warning:

```
[vite] hmr invalidate /src/routes/session.tsx Could not Fast Refresh ("messages" export is incompatible). Learn more at https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#consistent-components-exports
```

How to address this issue?

**Comment by ai** [comment]
> How to address this issue?

You can move `messages` to another file like `src/compoentns/route/messages.ts`

Or you can you standard hot-reload instead of Fast Refresh.

**Comment by openscript** [comment]
Thank you for your quick reply. For what reason the `messages` need to be exported?

**Comment by ai** [comment]
To be used in script to collect all your current messages (and give JSON to translation platform). If you don’t need it, you can avoid exporting it.

**Comment by openscript** [comment]
> You can move messages to another file like src/compoentns/route/messages.ts

This one has the downside, that the i18n definition of each component is separated from the component. Per component another file needs to be created. The project becomes confusing.

> Or you can you standard hot-reload instead of Fast Refresh.

It's the official way to reload React components: https://github.com/facebook/react/tree/main/packages/react-refresh

---

I've been thinking how to solve this issue. Maybe we can export the messages alongside the component as a default export? This library would always try to read the `messages` property inside the default export?

```tsx
import { Button, Container, Paper, PasswordInput, TextInput, Title } from "@quassel/ui";
import { createFileRoute, RouteDefinition } from "@tanstack/react-router";
import { i18n } from "../stores/i18n";
import { useStore } from "@nanostores/react";

// Define the messages structure
const messages = i18n("sessionRoute", {
  title: "Sign in",
  emailLabel: "Email",
  emailPlaceholder: "fraenzy.tobler@example.ch",
});

// Define a utility type to add `messages` to the original Route type
type RouteWithMessages<T extends RouteDefinition> = T & {
  messages: typeof messages;
};

// Create the route
const baseRoute = createFileRoute("/session")({
  component: () => {
    const t = useStore(messages);
    return (
      <Container size={420} my={40}>
        <Title ta="center">{t.title}</Title>

        <Paper withBorder shadow="md" p={30} mt={30} radius="md">
          <TextInput label={t.emailLabel} placeholder={t.emailPlaceholder} required />
          <PasswordInput label="Password" placeholder="Your password" required mt="md" />
          <Button fullWidth mt="xl">
            Sign in
          </Button>
        </Paper>
      </Container>
    );
  },
});

// Extend the route with the messages property
const Route: RouteWithMessages<typeof baseRoute> = {
  ...baseRoute,
  messages,
};

// Default export of Route
export default Route;
```

I18n would be looking for `defaultExportedRoute.messages`. The current implementation keeps existing and this is an additional behavior. It is also not locked to React. The framework agnostic character remains.

**Comment by ai** [comment]
Do you really need to export `messages`? Do you plan to use JSON generator script?

Another idea to keep script, is to not export messages but just parse JS file.

**Comment by openscript** [comment]
I've tried to implement a JSON generator script, but it isn't that easy. I need calculate a diff to the existing json files, otherwise it will override translated values. Our translation service directly saves the changes into the git repos json files.

Parsing the scripts and extract it this way, is likely to be more effort.

**Comment by ai** [comment]
Another way is just to do `Route.messages = messages`

**Comment by openscript** [comment]
> Another way is just to do `Route.messages = messages`

Yes, but as I remember it's more difficult to achieve proper TS typing.
