### ISSUE TITLE
Clears data from local storage after page refresh

### ISSUE THREAD

**Issue by azat-io** [nanostores/i18n#4]
Trying to use this package with `@nanostores/persistent` and cannot save language settings. My locale data is deleting after page refresh.

![Screen Recording](https://user-images.githubusercontent.com/5698350/141507490-70251e81-8460-4d2f-8da2-da385c18a96f.gif)

You can try to check the problem here:
https://si5dw.csb.app/

Source code:
https://codesandbox.io/s/nanostores-i18n-si5dw

**Comment by ai** [comment]
Thanks for very well-formed issue report.

The quick fix is to move `i18n()` functions out from React component:

```js
let messages = i18n("hello", {
  helloWorld: "Hello World"
});

export default () => {
  const t = useStore(messages);
```

We can detect when component was defined with the same name and print a warning to avoid these mistakes in the future. What do you think?

**Comment by azat-io** [comment]
Thanks for the answer!

Also I need to know which language was selected on app first render. I'm creating `persistentAtom` store which default value is `undefined` and put it as `localeSettings` to my `createI18n()` function. Is there any way to update atom store from `localeSettings` [here](https://github.com/nanostores/i18n/blob/main/browser/index.js#L15)?

![image](https://user-images.githubusercontent.com/5698350/141534383-9f24ae39-4301-400a-83ba-32841aa06921.png)

**Comment by ai** [comment]
> Is there any way to update atom store from localeSettings here?

I recommend to set `localeSettings` store only when user manually changed locale.

The reason is in this use case:

1. User with Russian browser visited webapp
2. Webapp have only Wnglish and French locales
3. `browser` locale auto-detect store decided to use English locale.
4. A few months later, webapp get Russian translation
5. Old users will not see new Russian translation because after first visit English locale was written in `localStorage`

> Also I need to know which language was selected on app first render

Can you use `locale` store (created by `localeFrom`)? This store was created to be the single source of truth of current locale.

**Comment by azat-io** [comment]
> I recommend to set localeSettings store only when user manually changed locale.

Agree with you, thanks!

And the last question: it looks like there is a problem with deleting language data from storage after opening the site in the second browser tab

![Untitled](https://user-images.githubusercontent.com/5698350/141593825-316d5f60-5f24-4dee-8acb-96d966baeede.gif)

**Comment by ai** [comment]
I added check to prevent multiple definitions 0344aa4

>  it looks like there is a problem with deleting language data from storage after opening the site in the second browser tab

Very strange. Can you repate the issue with another `@nanostores/persistance` store outside of I18n?

**Comment by azat-io** [comment]
> Very strange. Can you repeat the issue with another @nanostores/persistance store outside of I18n?

I have updated my [test web page](https://si5dw.csb.app/). Looks like this is a problem with `@nanostores/persistent` package. Sorry.

**Comment by ai** [comment]
Can you open another issue there to track them separately?

**Comment by azat-io** [comment]
https://github.com/nanostores/persistent/issues/14
